dist: trusty
language: java
jdk: openjdk15
sudo: false
script:
  - mvn test
  - sonar-scanner

env:
  global:
    - CC_TEST_REPORTER_ID=9cc8d6f658996ba4d94c148c02e551e3be69977dc930054b442cfcccc775ec3d
    - SONAR_TOKEN=Q1QK+jUobWRE2xe8oKSbPnT0vlI50UlKCBsTl+4JMB1F6Obrdqj7krY0MSvy0WBXxjHtshwaXxzcT0Qsx90UeenMtgfLx3B9Hiz0n4W/Ua7ZtDfVFTB+BNgtNcsvyls+kWGPBO56lobxAJUbsS67SxXHGPvNmnQaTnI2e3wsX6d8P6ZNfeCT45o7wWXKQHvAMrYW/P6OPpTZQDvFQQIMB4nHmc3gRAwknVTsW5j4/gA+N49df4zm0ZpkaGY/Sm+nqE8e/c1t7er0w6kpnxMRlfJNIO4/ECO8fH336mv3/i18ZG2bhFjF+0wXeoWmxQlxGpYB4yGr7TfC/ufqWwWsplwUt3wSrM8v7h/UYCvTSyu97EONEoL0D7ps6nGuMCAQbaplY7PJJ3QH9glw5B0Pn1MmnJW8fxVJe5MAytIoC4hjHQ2fg0jC4TT4bAtzpxgIiPMWkheeUYecU1i4NAjLFNpiMvoeYxmyKru4ET9KOdyqDiKPNPvcLgmM23uMutshXLIuhTjCvdN41gyx+0md4PuQExgzu8b/bzdpwEbpp6mpYsHr/b+2SBsy59/NwIGIPEeFs8mxJv5VDagznyJySqIWB80tKv8ZcOkQTui4rND8Z5VOpRIbIlU/a583ak2E35Q2pRUHuk6Crp5n8NrQgvko2EgQmjb0XfbxQErOWUE=

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter format-coverage target/jacoco-ut/jacoco.xml  --input-type jacoco
  - ./cc-test-reporter upload-coverage

addons:
  sonarcloud:
    organization: "apssouza22-github"
    token:
      secure: "Q1QK+jUobWRE2xe8oKSbPnT0vlI50UlKCBsTl+4JMB1F6Obrdqj7krY0MSvy0WBXxjHtshwaXxzcT0Qsx90UeenMtgfLx3B9Hiz0n4W/Ua7ZtDfVFTB+BNgtNcsvyls+kWGPBO56lobxAJUbsS67SxXHGPvNmnQaTnI2e3wsX6d8P6ZNfeCT45o7wWXKQHvAMrYW/P6OPpTZQDvFQQIMB4nHmc3gRAwknVTsW5j4/gA+N49df4zm0ZpkaGY/Sm+nqE8e/c1t7er0w6kpnxMRlfJNIO4/ECO8fH336mv3/i18ZG2bhFjF+0wXeoWmxQlxGpYB4yGr7TfC/ufqWwWsplwUt3wSrM8v7h/UYCvTSyu97EONEoL0D7ps6nGuMCAQbaplY7PJJ3QH9glw5B0Pn1MmnJW8fxVJe5MAytIoC4hjHQ2fg0jC4TT4bAtzpxgIiPMWkheeUYecU1i4NAjLFNpiMvoeYxmyKru4ET9KOdyqDiKPNPvcLgmM23uMutshXLIuhTjCvdN41gyx+0md4PuQExgzu8b/bzdpwEbpp6mpYsHr/b+2SBsy59/NwIGIPEeFs8mxJv5VDagznyJySqIWB80tKv8ZcOkQTui4rND8Z5VOpRIbIlU/a583ak2E35Q2pRUHuk6Crp5n8NrQgvko2EgQmjb0XfbxQErOWUE=" # encrypted value of your token
